/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	flowv1alpha1 "volcano.sh/apis/pkg/apis/flow/v1alpha1"
)

// BackoffPolicyApplyConfiguration represents a declarative configuration of the BackoffPolicy type for use
// with apply.
type BackoffPolicyApplyConfiguration struct {
	Type      *flowv1alpha1.BackoffType `json:"type,omitempty"`
	BaseDelay *v1.Duration              `json:"baseDelay,omitempty"`
	MaxDelay  *v1.Duration              `json:"maxDelay,omitempty"`
}

// BackoffPolicyApplyConfiguration constructs a declarative configuration of the BackoffPolicy type for use with
// apply.
func BackoffPolicy() *BackoffPolicyApplyConfiguration {
	return &BackoffPolicyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BackoffPolicyApplyConfiguration) WithType(value flowv1alpha1.BackoffType) *BackoffPolicyApplyConfiguration {
	b.Type = &value
	return b
}

// WithBaseDelay sets the BaseDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDelay field is set to the value of the last call.
func (b *BackoffPolicyApplyConfiguration) WithBaseDelay(value v1.Duration) *BackoffPolicyApplyConfiguration {
	b.BaseDelay = &value
	return b
}

// WithMaxDelay sets the MaxDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDelay field is set to the value of the last call.
func (b *BackoffPolicyApplyConfiguration) WithMaxDelay(value v1.Duration) *BackoffPolicyApplyConfiguration {
	b.MaxDelay = &value
	return b
}
