/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	batchv1alpha1 "volcano.sh/apis/pkg/apis/batch/v1alpha1"
	applyconfigurationbatchv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/batch/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// ReservationsGetter has a method to return a ReservationInterface.
// A group's client should implement this interface.
type ReservationsGetter interface {
	Reservations(namespace string) ReservationInterface
}

// ReservationInterface has methods to work with Reservation resources.
type ReservationInterface interface {
	Create(ctx context.Context, reservation *batchv1alpha1.Reservation, opts v1.CreateOptions) (*batchv1alpha1.Reservation, error)
	Update(ctx context.Context, reservation *batchv1alpha1.Reservation, opts v1.UpdateOptions) (*batchv1alpha1.Reservation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, reservation *batchv1alpha1.Reservation, opts v1.UpdateOptions) (*batchv1alpha1.Reservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*batchv1alpha1.Reservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*batchv1alpha1.ReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchv1alpha1.Reservation, err error)
	Apply(ctx context.Context, reservation *applyconfigurationbatchv1alpha1.ReservationApplyConfiguration, opts v1.ApplyOptions) (result *batchv1alpha1.Reservation, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, reservation *applyconfigurationbatchv1alpha1.ReservationApplyConfiguration, opts v1.ApplyOptions) (result *batchv1alpha1.Reservation, err error)
	ReservationExpansion
}

// reservations implements ReservationInterface
type reservations struct {
	*gentype.ClientWithListAndApply[*batchv1alpha1.Reservation, *batchv1alpha1.ReservationList, *applyconfigurationbatchv1alpha1.ReservationApplyConfiguration]
}

// newReservations returns a Reservations
func newReservations(c *BatchV1alpha1Client, namespace string) *reservations {
	return &reservations{
		gentype.NewClientWithListAndApply[*batchv1alpha1.Reservation, *batchv1alpha1.ReservationList, *applyconfigurationbatchv1alpha1.ReservationApplyConfiguration](
			"reservations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *batchv1alpha1.Reservation { return &batchv1alpha1.Reservation{} },
			func() *batchv1alpha1.ReservationList { return &batchv1alpha1.ReservationList{} },
		),
	}
}
