/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	schedulingv1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
)

// ReservationLister helps list Reservations.
// All objects returned here must be treated as read-only.
type ReservationLister interface {
	// List lists all Reservations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1beta1.Reservation, err error)
	// Reservations returns an object that can list and get Reservations.
	Reservations(namespace string) ReservationNamespaceLister
	ReservationListerExpansion
}

// reservationLister implements the ReservationLister interface.
type reservationLister struct {
	listers.ResourceIndexer[*schedulingv1beta1.Reservation]
}

// NewReservationLister returns a new ReservationLister.
func NewReservationLister(indexer cache.Indexer) ReservationLister {
	return &reservationLister{listers.New[*schedulingv1beta1.Reservation](indexer, schedulingv1beta1.Resource("reservation"))}
}

// Reservations returns an object that can list and get Reservations.
func (s *reservationLister) Reservations(namespace string) ReservationNamespaceLister {
	return reservationNamespaceLister{listers.NewNamespaced[*schedulingv1beta1.Reservation](s.ResourceIndexer, namespace)}
}

// ReservationNamespaceLister helps list and get Reservations.
// All objects returned here must be treated as read-only.
type ReservationNamespaceLister interface {
	// List lists all Reservations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1beta1.Reservation, err error)
	// Get retrieves the Reservation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1beta1.Reservation, error)
	ReservationNamespaceListerExpansion
}

// reservationNamespaceLister implements the ReservationNamespaceLister
// interface.
type reservationNamespaceLister struct {
	listers.ResourceIndexer[*schedulingv1beta1.Reservation]
}
