/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ReservationOwnerApplyConfiguration represents a declarative configuration of the ReservationOwner type for use
// with apply.
type ReservationOwnerApplyConfiguration struct {
	Object        *v1.ObjectReference                     `json:"object,omitempty"`
	LabelSelector *metav1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
}

// ReservationOwnerApplyConfiguration constructs a declarative configuration of the ReservationOwner type for use with
// apply.
func ReservationOwner() *ReservationOwnerApplyConfiguration {
	return &ReservationOwnerApplyConfiguration{}
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *ReservationOwnerApplyConfiguration) WithObject(value v1.ObjectReference) *ReservationOwnerApplyConfiguration {
	b.Object = &value
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *ReservationOwnerApplyConfiguration) WithLabelSelector(value *metav1.LabelSelectorApplyConfiguration) *ReservationOwnerApplyConfiguration {
	b.LabelSelector = value
	return b
}
