/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ReservationStatusApplyConfiguration represents a declarative configuration of the ReservationStatus type for use
// with apply.
type ReservationStatusApplyConfiguration struct {
	State           *ReservationStateApplyConfiguration      `json:"phase,omitempty"`
	MinAvailable    *int32                                   `json:"minAvailable,omitempty"`
	TaskStatusCount map[string]TaskStateApplyConfiguration   `json:"taskStatusCount,omitempty"`
	Pending         *int32                                   `json:"pending,omitempty"`
	Available       *int32                                   `json:"available,omitempty"`
	Succeeded       *int32                                   `json:"succeeded,omitempty"`
	Failed          *int32                                   `json:"failed,omitempty"`
	Conditions      []ReservationConditionApplyConfiguration `json:"conditions,omitempty"`
	CurrentOwner    *v1.ObjectReference                      `json:"currentOwner,omitempty"`
	Allocatable     *v1.ResourceList                         `json:"allocatable,omitempty"`
	Allocated       *v1.ResourceList                         `json:"allocated,omitempty"`
}

// ReservationStatusApplyConfiguration constructs a declarative configuration of the ReservationStatus type for use with
// apply.
func ReservationStatus() *ReservationStatusApplyConfiguration {
	return &ReservationStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithState(value *ReservationStateApplyConfiguration) *ReservationStatusApplyConfiguration {
	b.State = value
	return b
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithMinAvailable(value int32) *ReservationStatusApplyConfiguration {
	b.MinAvailable = &value
	return b
}

// WithTaskStatusCount puts the entries into the TaskStatusCount field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the TaskStatusCount field,
// overwriting an existing map entries in TaskStatusCount field with the same key.
func (b *ReservationStatusApplyConfiguration) WithTaskStatusCount(entries map[string]TaskStateApplyConfiguration) *ReservationStatusApplyConfiguration {
	if b.TaskStatusCount == nil && len(entries) > 0 {
		b.TaskStatusCount = make(map[string]TaskStateApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.TaskStatusCount[k] = v
	}
	return b
}

// WithPending sets the Pending field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pending field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithPending(value int32) *ReservationStatusApplyConfiguration {
	b.Pending = &value
	return b
}

// WithAvailable sets the Available field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Available field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithAvailable(value int32) *ReservationStatusApplyConfiguration {
	b.Available = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithSucceeded(value int32) *ReservationStatusApplyConfiguration {
	b.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithFailed(value int32) *ReservationStatusApplyConfiguration {
	b.Failed = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ReservationStatusApplyConfiguration) WithConditions(values ...*ReservationConditionApplyConfiguration) *ReservationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithCurrentOwner sets the CurrentOwner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentOwner field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithCurrentOwner(value v1.ObjectReference) *ReservationStatusApplyConfiguration {
	b.CurrentOwner = &value
	return b
}

// WithAllocatable sets the Allocatable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allocatable field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithAllocatable(value v1.ResourceList) *ReservationStatusApplyConfiguration {
	b.Allocatable = &value
	return b
}

// WithAllocated sets the Allocated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allocated field is set to the value of the last call.
func (b *ReservationStatusApplyConfiguration) WithAllocated(value v1.ResourceList) *ReservationStatusApplyConfiguration {
	b.Allocated = &value
	return b
}
