/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	batchv1alpha1 "volcano.sh/apis/pkg/apis/batch/v1alpha1"
)

// ReservationStateApplyConfiguration represents a declarative configuration of the ReservationState type for use
// with apply.
type ReservationStateApplyConfiguration struct {
	Phase              *batchv1alpha1.ReservationPhase `json:"phase,omitempty"`
	Reason             *string                         `json:"reason,omitempty"`
	Message            *string                         `json:"message,omitempty"`
	LastTransitionTime *v1.Time                        `json:"lastTransitionTime,omitempty"`
}

// ReservationStateApplyConfiguration constructs a declarative configuration of the ReservationState type for use with
// apply.
func ReservationState() *ReservationStateApplyConfiguration {
	return &ReservationStateApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ReservationStateApplyConfiguration) WithPhase(value batchv1alpha1.ReservationPhase) *ReservationStateApplyConfiguration {
	b.Phase = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ReservationStateApplyConfiguration) WithReason(value string) *ReservationStateApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ReservationStateApplyConfiguration) WithMessage(value string) *ReservationStateApplyConfiguration {
	b.Message = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *ReservationStateApplyConfiguration) WithLastTransitionTime(value v1.Time) *ReservationStateApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
