/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	shardv1alpha1 "volcano.sh/apis/pkg/apis/shard/v1alpha1"
)

// NodeShardLister helps list NodeShards.
// All objects returned here must be treated as read-only.
type NodeShardLister interface {
	// List lists all NodeShards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*shardv1alpha1.NodeShard, err error)
	// NodeShards returns an object that can list and get NodeShards.
	NodeShards(namespace string) NodeShardNamespaceLister
	NodeShardListerExpansion
}

// nodeShardLister implements the NodeShardLister interface.
type nodeShardLister struct {
	listers.ResourceIndexer[*shardv1alpha1.NodeShard]
}

// NewNodeShardLister returns a new NodeShardLister.
func NewNodeShardLister(indexer cache.Indexer) NodeShardLister {
	return &nodeShardLister{listers.New[*shardv1alpha1.NodeShard](indexer, shardv1alpha1.Resource("nodeshard"))}
}

// NodeShards returns an object that can list and get NodeShards.
func (s *nodeShardLister) NodeShards(namespace string) NodeShardNamespaceLister {
	return nodeShardNamespaceLister{listers.NewNamespaced[*shardv1alpha1.NodeShard](s.ResourceIndexer, namespace)}
}

// NodeShardNamespaceLister helps list and get NodeShards.
// All objects returned here must be treated as read-only.
type NodeShardNamespaceLister interface {
	// List lists all NodeShards in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*shardv1alpha1.NodeShard, err error)
	// Get retrieves the NodeShard from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*shardv1alpha1.NodeShard, error)
	NodeShardNamespaceListerExpansion
}

// nodeShardNamespaceLister implements the NodeShardNamespaceLister
// interface.
type nodeShardNamespaceLister struct {
	listers.ResourceIndexer[*shardv1alpha1.NodeShard]
}
