/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// BunchPolicySpecApplyConfiguration represents a declarative configuration of the BunchPolicySpec type for use
// with apply.
type BunchPolicySpecApplyConfiguration struct {
	Name            *string                                `json:"name,omitempty"`
	MatchPolicy     []MatchPolicySpecApplyConfiguration    `json:"matchPolicy,omitempty"`
	NetworkTopology *NetworkTopologySpecApplyConfiguration `json:"networkTopology,omitempty"`
	BunchSize       *int32                                 `json:"bunchSize,omitempty"`
}

// BunchPolicySpecApplyConfiguration constructs a declarative configuration of the BunchPolicySpec type for use with
// apply.
func BunchPolicySpec() *BunchPolicySpecApplyConfiguration {
	return &BunchPolicySpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BunchPolicySpecApplyConfiguration) WithName(value string) *BunchPolicySpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithMatchPolicy adds the given value to the MatchPolicy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchPolicy field.
func (b *BunchPolicySpecApplyConfiguration) WithMatchPolicy(values ...*MatchPolicySpecApplyConfiguration) *BunchPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatchPolicy")
		}
		b.MatchPolicy = append(b.MatchPolicy, *values[i])
	}
	return b
}

// WithNetworkTopology sets the NetworkTopology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkTopology field is set to the value of the last call.
func (b *BunchPolicySpecApplyConfiguration) WithNetworkTopology(value *NetworkTopologySpecApplyConfiguration) *BunchPolicySpecApplyConfiguration {
	b.NetworkTopology = value
	return b
}

// WithBunchSize sets the BunchSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BunchSize field is set to the value of the last call.
func (b *BunchPolicySpecApplyConfiguration) WithBunchSize(value int32) *BunchPolicySpecApplyConfiguration {
	b.BunchSize = &value
	return b
}
