/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SubGroupPolicySpecApplyConfiguration represents a declarative configuration of the SubGroupPolicySpec type for use
// with apply.
type SubGroupPolicySpecApplyConfiguration struct {
	Name            *string                                `json:"name,omitempty"`
	MatchPolicy     []MatchPolicySpecApplyConfiguration    `json:"matchPolicy,omitempty"`
	NetworkTopology *NetworkTopologySpecApplyConfiguration `json:"networkTopology,omitempty"`
	SubGroupSize    *int32                                 `json:"subGroupSize,omitempty"`
	MinSubGroups    *int32                                 `json:"minSubGroups,omitempty"`
}

// SubGroupPolicySpecApplyConfiguration constructs a declarative configuration of the SubGroupPolicySpec type for use with
// apply.
func SubGroupPolicySpec() *SubGroupPolicySpecApplyConfiguration {
	return &SubGroupPolicySpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubGroupPolicySpecApplyConfiguration) WithName(value string) *SubGroupPolicySpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithMatchPolicy adds the given value to the MatchPolicy field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchPolicy field.
func (b *SubGroupPolicySpecApplyConfiguration) WithMatchPolicy(values ...*MatchPolicySpecApplyConfiguration) *SubGroupPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatchPolicy")
		}
		b.MatchPolicy = append(b.MatchPolicy, *values[i])
	}
	return b
}

// WithNetworkTopology sets the NetworkTopology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkTopology field is set to the value of the last call.
func (b *SubGroupPolicySpecApplyConfiguration) WithNetworkTopology(value *NetworkTopologySpecApplyConfiguration) *SubGroupPolicySpecApplyConfiguration {
	b.NetworkTopology = value
	return b
}

// WithSubGroupSize sets the SubGroupSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupSize field is set to the value of the last call.
func (b *SubGroupPolicySpecApplyConfiguration) WithSubGroupSize(value int32) *SubGroupPolicySpecApplyConfiguration {
	b.SubGroupSize = &value
	return b
}

// WithMinSubGroups sets the MinSubGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSubGroups field is set to the value of the last call.
func (b *SubGroupPolicySpecApplyConfiguration) WithMinSubGroups(value int32) *SubGroupPolicySpecApplyConfiguration {
	b.MinSubGroups = &value
	return b
}
